### ISSUE TITLE
Using lab types in generic type arguments

### ISSUE THREAD

**Issue by stoprightthere** [wesselb/lab#4]
How does one properly typehint with `lab` types as arguments for generic types? E.g
```python
import lab as B
from typing import Mapping

Mapping[str, B.Numeric]
```
raises `TypeError: issubclass() arg 1 must be a class` (Python>=3.7)  because `B.Numeric` is not recognized as a type.

**Comment by wesselb** [comment]
LAB types are unfortunately not `type`s, which is why you're getting that error. The current solution is that Plum provides versions of the generic types which are compatible with LAB types. E.g.,

```python
>>> import lab as B

>>> from plum import Sequence

>>> Sequence[B.Numeric]
Sequence[lab.types.Numeric]
```

As it stands right now, Plum doesn't provide a version of `Mapping`. If you'd like support for `Mapping`, please open an issue [here](https://github.com/wesselb/plum/issues). Alternatively, if it would be possible in your design, Plum does provide a version of the `Dict` generic type, which you could use:

```python
>>> import lab as B

>>> from plum import Dict

>>> Dict[str, B.Numeric]
Dict[builtins.str, lab.types.Numeric]
```

Note that, currently, all types in Plum's type system are _covariant_. As per [this comment](https://stackoverflow.com/questions/52487663/python-type-hints-typing-mapping-vs-typing-dict/52487800#comment113661999_52487800), this behaviour not completely true to Python's generics, which specify that `Dict` should be invariant.

On the long term, I intend to refactor Plum types (LAB types are Plum types) to be true `type`s, so this issue should then disappear. (I'm soon to be in the writing-up phase of the PhD, so I'm not sure when this would be.)

**Comment by stoprightthere** [comment]
Thanks a lot! I think `Dict` will suit our needs. Good luck with your writing-up :)

I'm closing the issue.

**Comment by wesselb** [comment]
Thanks, @stoprightthere! :) Glad that `Dict` also suits your needs.
